### ISSUE TITLE
Stop returning album links

### ISSUE THREAD

**Issue by andrewmwilson** [juanpabloaj/slack-imgur#2]
I assume this isn't intentional?

**Comment by juanpabloaj** [comment]
@andrewmwilson thanks for reporting.

Yes, isn't intentional, I will try to fix the issue as soon as posible ;)

**Comment by andrewmwilson** [comment]
Thanks!

**Comment by juanpabloaj** [comment]
@andrewmwilson the commit 8c1a09a01c393390213c32fe1bae7f64362326a5 fix the issue, if now work fine please close the issue ;)

**Comment by andrewmwilson** [comment]
Thanks!
